# Generated by Django 2.2.9 on 2021-08-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210807_1556'),
        ('posts', '0004_auto_20210727_1033'),
    ]

    operations = [
    ]
