# Generated by Django 2.2.6 on 2021-10-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211018_0122'),
        ('posts', '0006_auto_20211014_1532'),
    ]

    operations = [
    ]
