# Generated by Django 2.2.6 on 2021-11-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211004_1317'),
        ('posts', '0007_merge_20211020_0116'),
    ]

    operations = [
    ]
